### PR TITLE
Update style

### PR DESCRIPTION
**Pull request by codeboyQ2n5ha45**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [x] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [x] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No. The existing formula is already broken as it has not been maintained.

### Describe the changes you're proposing

This re-implements Zookeeper installation and configuration based on the SaltStack Template Formula.

### Documentation checklist

- [x] Updated the `README` (e.g. `Available states`).
- [x] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Review by noelmcloughlin — CHANGES_REQUESTED** [review]
Thanks @codeboyQ2n5ha45  I reviewed and looks good.

One minor issue - we use https://github.com/semantic-release/semantic-release  in this organization. Its very popular across open source. But it has rules that commit messages must follow `keyword(domain): text` format.  This means that instead of your messages

   feat: update to working version
   docs: add pillar example 
   style: adjust style for pr

Can I suggest

   feat(formula): update to working version
   docs(example): add pillar example
   chore(style): adjust style for pr

You could lookup rebasing (git rebase -i HEAD~3) and modify that way.  I might be able to modify the commit messages when merging but its good learning experience for you to solve this problem if thats okay.  Then we can see about merging.

**Comment by codeboyQ2n5ha45** [comment]
> Thanks @codeboyQ2n5ha45 I reviewed and looks good.
> 
> One minor issue - we use https://github.com/semantic-release/semantic-release in this organization. Its very popular across open source. But it has rules that commit messages must follow `keyword(domain): text` format. This means that instead of your messages
> 
> feat: update to working version
> docs: add pillar example
> style: adjust style for pr
> 
> Can I suggest
> 
> feat(formula): update to working version
> docs(example): add pillar example
> chore(style): adjust style for pr
> 
> You could lookup rebasing (git rebase -i HEAD~3) and modify that way. I might be able to modify the commit messages when merging but its good learning experience for you to solve this problem if thats okay. Then we can see about merging.

Ok. Thanks for reviewing. I'll try and make those semantics changes and get back to you in the next couple days.

**Comment by codeboyQ2n5ha45** [comment]
@noelmcloughlin   I think I've renamed properly.  Thanks was a good learning experience.

**Comment by noelmcloughlin** [comment]
Thanks, that's good.  This PR changes lots of files and it is impossible for a reviewer to know if the saltstack-formulas "infra" files (i.e. yamls, rules, lints) are ideal but that question is out of scope for this PR.   I saw word "subcomponent" mentioned in one of the SLS files - probably you do not want references to "subcomponent" in this PR.  Could you check? @codeboyQ2n5ha45 

I glanced over the following files .....

.gitignore
.pre-commit-config.yaml
.rstcheck.cfg
.rubocop.yml
.salt.lint
.travis.yml
.yamllint
CODEOWNERS
FORMULA
Gemfile
Gemfile.lock
LICENSE
bin/install-hooks
bin/kitchen
commitlint.config.js
docs/README.rst
kitchen.yml
pillar.example   (no newline at end of file)
pre-commit_semantic-release.sh
release-rules.js
release-config.js
test/integration/..
test/salt/..
zookeeper/archive
zookeeper/clean.sls    [subcomponent]
zookeeper/files/..

**Comment by noelmcloughlin** [comment]
Hi   @codeboyQ2n5ha45 if you can remove "subcomponent" from the PR this can be merged.

**Pull request merged**
