### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by jackscott**

### CODE REVIEW

**Comment by jackscott** [comment]
Rework how the zk user is created.

**Comment by jackscott** [comment]
sorry ya'll accidentiality opened a PR to the wrong repo

**Comment by sroegner** [comment]
@jackscott: Just out of interest: did you test the move to ip addresses in a multi-homed environment?

**Comment by jackscott** [comment]
@sroegner - good point, I'm running my ensemble on machines with one NIC.

I think I have a way to set `myid` and `connection_string` without using `get_hostname`, still testing though...

**Pull request closed without merging**
