### PR TITLE
[tests] reduce verbosity of test run

### PR DESCRIPTION
**Pull request by blbradley**
`debug` was too much for Travis. Is this better?

### CODE REVIEW

**Comment by blbradley** [comment]
It's still too long for Travis due to the output of archive.extracted. Maybe that could be shortened.

**Comment by sroegner** [comment]
Thanks a lot @blbradley

**Comment by blbradley** [comment]
`archive.extracted` docs:

>trim_output
>: False
>
>    Useful for archives with many files in them. This can either be set to True (in which case only the first 100 files extracted will be in the state results), or it can be set to an integer for more exact control over the max number of files to include in the state results.
>
>    New in version 2016.3.0.

Can we use this parameter? Is it too new?

**Comment by vutny** [comment]
I think we can finally merge this.

**Pull request merged**
